# Generated by Django 5.2.1 on 2025-05-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catchup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.URLField(default='https://example.com/default.jpg'),
        ),
    ]
